version: 0.1
dev:
  global:
    parameters:
      stack_name: tagmemo
      region: ap-northeast-1
      tags:
        - Administrator=suz-ry
        - GitHub=https://github.com/Ryo-Suzukii/tagmemo
  deploy:
    parameters:
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
    confirm_changeset: true
    s3_bucket: dev-suz-ry-sam-template
    s3_prefix: tagmemo
  sync:
    parameters:
      s3-bucket: dev-suz-ry-sam-template
      s3-prefix: tagmemo

prod:
  global:
    parameters:
      stack_name: tagmemo
      region: ap-northeast-1
      tags:
        - Administrator=suz-ry
        - GitHub=https://github.com/Ryo-Suzukii/tagmemo
  deploy:
    parameters:
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
    confirm_changeset: true
    s3_bucket: suz-ry-sam-template
    s3_prefix: tagmemo
